FROM apache/kafka:latest

# Node identity
ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller

# Listeners
ENV KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

# 3 voters (KRaft quorum)
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker1:9093,2@broker2:9093,3@broker3:9093

# Replication & offsets topic (3 nodes / 3 partitions)
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
ENV KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=3
ENV KAFKA_DEFAULT_REPLICATION_FACTOR=3
ENV KAFKA_MIN_IN_SYNC_REPLICAS=2

# Transaction log (matches 3-node setup)
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2

# Default partitions per topic
ENV KAFKA_NUM_PARTITIONS=3

# Data directory
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data

EXPOSE 9092 9093

CMD ["/opt/kafka/bin/kafka-server-start.sh", "/opt/kafka/config/kraft/server.properties"]
