name: 2 Hello World

on:
  workflow_dispatch:
env:
  APP_ENV: "dev"  
jobs:
  ved-demo:
    runs-on: ubuntu-latest
    steps:
      - name: connect to ENV
        run: echo "connected to ${{ vars.APP_ENV}}"
