name: Hello World
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-22.04
   steps:
     - name: Hello steps
       run: echo "welcome to my world"
       run: echo "we have started the job"
   
