name: Hello World

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          echo "Running build stage..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: |
          echo "Running test stage..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy app
        run: |
          echo "Running deploy stage..."
          
              
