name: context variables 

on:
  push:
jobs:
  context-variable:
    runs-on: ubuntu latest 
    steps:
      - name: contect vars used continue-on-error
        run: |
          echo "this workflow is tigered by ${{ github.actor}}"
          echo "the repository name is ${{github.action_repository}}"
      
